name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

# ... existing code ...
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your Node.js version
      - name: Install dependencies
        run: npm install # Or yarn install
        working-directory: portfolio-adeore
      - name: Build application
        run: npm run build # Or yarn build
        working-directory: portfolio-adeore
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: portfolio-adeore/build # Or your build output directory (e.g., ./dist)